{{- if .Values.memcached.metrics.podMonitor.enabled      }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ template "fullname" . }}-memcache
  labels:
    openshift.io/prometheus-rule-evaluation-scope: leaf-prometheus
apiVersion: monitoring.coreos.com/v1
spec:
  groups:
  - name: memcached
    rules:
    - alert: MemcachedDown
      annotations:
        description: Memcached instance {{ "{{" }} $labels.job {{ "}}" }} / {{ "{{" }} $labels.instance {{ "}}" }} is down
          for more than 15 minutes.
        summary: Memcached instance is down.
      expr: |
        memcached_up == 0
      for: 15m
      labels:
        severity: critical
    - alert: MCrouterDown
      annotations:
        description: MCRouter instance {{ "{{" }} $labels.job {{ "}}" }} / {{ "{{" }} $labels.instance {{ "}}" }} is down
          for more than 15 minutes.
        summary: Memcached instance is down.
      expr: |
        mcrouter_up == 0
      for: 15m
      labels:
        severity: critical

    - alert: MemcachedConnectionLimitApproaching
      annotations:
        description: 80% connections is used 
        summary: Memcached max connection limit is approaching.
      expr: |
        (memcached_current_connections / memcached_max_connections * 100) > 80
      for: 15m
      labels:
        severity: warning

    - alert: MemcachedConnectionLimitApproaching
      annotations:
        description: 95% connections is used 
        summary: Memcached connections at critical level.
      expr: |
        (memcached_current_connections / memcached_max_connections * 100) > 95
      for: 15m
      labels:
        severity: critical


{{- end }}
