{{- if .Values.memcached.metrics.podMonitor.enabled	 }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ template "fullname" . }}-mc
spec:
  namespaceSelector: {}
  podMetricsEndpoints:
  - bearerTokenSecret:
      key: ""
    port: metrics
  selector:
    matchLabels:
      app: {{ template "fullname" . }}
{{- end }}
