apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name:  {{ template "name" . }}
spec:
  podSelector:
    matchLabels:
      app: {{ template "fullname" . }}
  policyTypes:
    - Egress
  egress:
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/instance: {{ template "name" . }}
              app.kubernetes.io/name: memcached
      ports:
        - protocol: TCP
          port:  {{ .Values.memcached.service.port }}



