{{- if .Values.memcached.metrics.podMonitor.enabled	 }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ template "fullname" . }}
spec:
  namespaceSelector: {}
  podMetricsEndpoints:
  - bearerTokenSecret:
      key: ""
    port: metrics
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ template "name" . }}
      app.kubernetes.io/name: memcached
{{- end }}
